while True:

    print('Calculator starts')

    print("          ┌──────────────────────┐")
    print("          │   ┌────────────────┐ │")
    print("          │   │ ON             │ │")
    print("          │   └────────────────┘ │")
    print("          │                      │")
    print("          │   ─── ─── ───   ───  │")
    print("          │  │ 7 │ 8 │ 9 │ │ + │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ 4 │ 5 │ 6 │ │ − │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ 1 │ 2 │ 3 │ │ x │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ · │ 0 │ = │ │ / │ │")
    print("          │  └───┴───┴───┘ └───┘ │")
    print("          └──────────────────────┘")

    a = int(input(' Enter the first number: '))
    b = int(input(' Enter the second number: '))

    c = a + b

    print("          ┌──────────────────────┐")
    print("          │   ┌────────────────┐ │")
    print("          │   │ Calculating... │ │")
    print("          │   └────────────────┘ │")
    print("          │                      │")
    print("          │   ─── ─── ───   ───  │")
    print("          │  │ 7 │ 8 │ 9 │ │ + │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ 4 │ 5 │ 6 │ │ − │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ 1 │ 2 │ 3 │ │ x │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ · │ 0 │ = │ │ / │ │")
    print("          │  └───┴───┴───┘ └───┘ │")
    print("          └──────────────────────┘")

    print('Answer =', c)

    print("Muliplication")

    son1 = int(input("How much do we multiply? - "))
    javob1 = c * son1

    print("          ┌──────────────────────┐")
    print("          │   ┌────────────────┐ │")
    print("          │   │ Calculating... │ │")
    print("          │   └────────────────┘ │")
    print("          │                      │")
    print("          │   ─── ─── ───   ───  │")
    print("          │  │ 7 │ 8 │ 9 │ │ + │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ 4 │ 5 │ 6 │ │ − │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ 1 │ 2 │ 3 │ │ x │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ · │ 0 │ = │ │ / │ │")
    print("          │  └───┴───┴───┘ └───┘ │")
    print("          └──────────────────────┘")

    print('Answer = ', javob1)

    son2 = int(input('How much do we divide by? - '))
    javob2 = javob1 / son2

    print("          ┌──────────────────────┐")
    print("          │   ┌────────────────┐ │")
    print("          │   │ Calculating... │ │")
    print("          │   └────────────────┘ │")
    print("          │                      │")
    print("          │   ─── ─── ───   ───  │")
    print("          │  │ 7 │ 8 │ 9 │ │ + │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ 4 │ 5 │ 6 │ │ − │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ 1 │ 2 │ 3 │ │ x │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ · │ 0 │ = │ │ / │ │")
    print("          │  └───┴───┴───┘ └───┘ │")
    print("          └──────────────────────┘")

    print('Javob = ', javob2)

    print('Calculator restarting')
    print('calculator restarted')

    print("          ┌──────────────────────┐")
    print("          │   ┌────────────────┐ │")
    print("          │   │ RESTARTED      │ │")
    print("          │   └────────────────┘ │")
    print("          │                      │")
    print("          │   ─── ─── ───   ───  │")
    print("          │  │ 7 │ 8 │ 9 │ │ + │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ 4 │ 5 │ 6 │ │ − │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ 1 │ 2 │ 3 │ │ x │ │")
    print("          │  ├───┼───┼───┤ ├───┤ │")
    print("          │  │ · │ 0 │ = │ │ / │ │")
    print("          │  └───┴───┴───┘ └───┘ │")
    print("          └──────────────────────┘")